# Site settings
title: mhdabdur
description: The journey start today
url: http://mhdabdur.github.io
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: abdur03

author:
  name: 'Muhammad Abdurrahman'
  email: mhd.abdur03@gmail.com
  twitter_username: mhdabdur03
  facebook_username: mmz.mhd
  github_username:  mhdabdur
  linkedin_username:  mhdabdur

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /blog/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jekyll-feed', 'jemoji']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
